name: diplom
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  tflite_flutter: ^0.11.0
  cupertino_icons: ^1.0.8
  image: ^4.1.3
  path_provider: ^2.1.2
  firebase_core: ^2.30.0
  firebase_storage:
  firebase_auth:
  image_picker:
  permission_handler: ^11.3.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  intl: ^0.20.2
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/model345.tflite
    - assets/labels.txt
    - assets/dataset1.png
    - assets/dataset2.png
    - assets/model100.tflite
    - assets/labels100.txt
